apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: local
    build:
      tagPolicy:
        sha256: { }
      artifacts:
        - image: indip-grafana-cloud-run
      local:
        useBuildkit: true
  - name: gcloud
    build:
      tagPolicy:
        sha256: { }
      artifacts:
        - image: europe-west6-docker.pkg.dev/gammadia-ch/dany/grafana-dev
      googleCloudBuild:
        projectId: gammadia-ch
        timeout: 1200s
